### ISSUE TITLE
CLI interface?

### ISSUE THREAD

**Issue by blasrodri** [kpanic/gigex#7]
Thanks for the amazing tool!
Would it be possible to have this functionality exported as a CLI?

**Comment by kpanic** [comment]
@blasrodri Thanks!  I could create an "escript", however that would require erlang and elixir installed still. It would not be a full binary go-or-rust like.
Would that work for you?

**Comment by blasrodri** [comment]
That would be a fine compromise! Thanks. It would be awesome

**Comment by kpanic** [comment]
I'll check it out in the next days 👍🏾

**Comment by kpanic** [comment]
Hey @blasrodri I opened https://github.com/kpanic/gigex/pull/8
The console output would be the same as the main application. i.e. it will print a list of maps.
Would it work for you? Alternatively I could create a small function to render a better formatted text.
Cheers

**Comment by blasrodri** [comment]
Thanks! It would be awesome if it could output json to a console. Then it's easy to work with, using tools like `jq` on the terminal.

**Comment by kpanic** [comment]
@blasrodri cool. I'll give a try by creating a proper renderer and not just `Jason.encode`.
One note though: This program was created for personal use, since it's scraping public websites I would suggest to use it in a gentle way if you are planning to automate the fetching of the concerts via command line.

**Comment by kpanic** [comment]
@blasrodri I added a json renderer to https://github.com/kpanic/gigex/pull/8
By default it's a map, but you can do `Gigex.gigs(renderer: :json)` or just execute the script.
Could you give it a try of this branch?

**Comment by blasrodri** [comment]
@kpanic thanks so much! I'll be giving it a go today. Need to see how to setup all infra to run elixir ^_^. And yes, I'll be a good digital citizen, I promise :)

**Comment by kpanic** [comment]
Hey @blasrodri I was curious to play with [burrito](https://github.com/burrito-elixir/burrito)
I opened another PR https://github.com/kpanic/gigex/pull/9 with `escript` (requires erlang/elixir) and `burrito` (should be self contained)
I updated also the README.

Note this https://github.com/kpanic/gigex/pull/9/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R166-R169 if you wanna go the self-executable binary way

**Comment by kpanic** [comment]
hey @blasrodri !
How is it going?

**Comment by kpanic** [comment]
@blasrodri any updates on this? otherwise I'll merge the PR

**Comment by blasrodri** [comment]
Thanks!! Please merge it

**Comment by kpanic** [comment]
Closing this issue. PR merged https://github.com/kpanic/gigex/pull/9
If you'll find some things to improve feel free to open another issue ;)
